# Project specification (.spec.toml)
# Shared configuration for featpy, testpy, and other tooling

# Global configuration (shared across all tools)
project_name = "blade-py"
languages = ['python']

exclude = [
    "**/tests/**",
    "**/target/**",
    "**/__pycache__/**",
]

# Feature documentation configuration (featpy)
[features]
features_root = "src"
docs_root = "docs/feats"
doc_pattern = "FEATURES_{FEATURE}.md"
auto_discover = false

